### ISSUE TITLE
{{ my_hostvars.ansible_user }}: 'str object' has no attribute 'ansible_user'

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#191]
## Issue

This playbook command
```
ansible-playbook $K8S_INFRA/hetzner/ansible/hetzner-create-server.yml -e vm_name=${VM_NAME}
-e salt_text=$(gpg --gen-random --armor 1 20) 
-e hetzner_context_name=snowdrop 
-e pass_provider=hetzner 
-e k8s_type=masters 
-e k8s_version=${k8s_version}
```

generates this error
```
TASK [hetzner/create_server : Template cloudinit file] *****************************************************************************************************************************************************************
task path: /Users/cmoullia/code/snowdrop/infra-jobs-productization/k8s-infra/ansible/roles/hetzner/create_server/tasks/main.yml:37
fatal: [localhost]: FAILED! => {"changed": false, 
"msg": "AnsibleUndefinedVariable: {{ my_hostvars.ansible_user }}: 
'str object' has no attribute 'ansible_user'"}
```

### How to reproduce
```
export k8s_version=118
export VM_NAME=h01-${k8s_version}
export PASSWORD_STORE_DIR=~/.password-store-snowdrop
export K8S_INFRA=~/code/snowdrop/infra-jobs-productization/k8s-infra
export ANSIBLE_ROLES_PATH="$K8S_INFRA/ansible/roles"

ansible-playbook $K8S_INFRA/hetzner/ansible/hetzner-delete-server.yml -e vm_name=${VM_NAME} -e hetzner_context_name=snowdrop
ansible-playbook $K8S_INFRA/ansible/playbook/passstore_controller_inventory_remove.yml -e vm_name=${VM_NAME}  -e pass_provider=hetzner
ansible-playbook $K8S_INFRA/ansible/playbook/passstore_controller_inventory.yml -e vm_name=${VM_NAME}  -e pass_provider=hetzner -e k8s_type=masters -e k8s_version=${k8s_version} -e operation=create
ansible-playbook $K8S_INFRA/hetzner/ansible/hetzner-create-server.yml -e vm_name=${VM_NAME} -e salt_text=$(gpg --gen-random --armor 1 20) -e hetzner_context_name=snowdrop -e pass_provider=hetzner -e k8s_type=masters -e k8s_version=${k8s_version}
ansible-playbook $K8S_INFRA/ansible/playbook/sec_host.yml -e vm_name=${VM_NAME} -e provider=hetzner
```

**Comment by cmoulliard** [comment]
The fix should be 

```
    - include_role:
        name: hetzner/create_server
      vars:
        vm_name: "{{ vm_name }}"
        # os_user: "{{ my_hostvars.ansible_user }}"
        os_user: "{{ query('passwordstore', 'hetzner/'+vm_name+'/os_user')[0] }}"
```
