### ISSUE TITLE
Remove (maybe) the duplicated instruction: passstore_controller_inventory.yml

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#209]
## Issue

The `passstore_controller_inventory.yml` file includes 2 [tasks](https://github.com/snowdrop/k8s-infra/blob/fde4717e93f50dfa4dc924ad21bf8ba31b8f58ff/ansible/playbook/passstore_controller_inventory.yml#L44-L67) very similar

```
    - name: "Execute create inventory, if tagged as so"
      include_role:
        name: "passstore/ansible_inventory"
        apply:
          tags:
            - always
      vars:
        pass_l1: "{{ pass_db_name | default('snowdrop') }}"
        pass_l2: "{{ pass_provider | default('hetzner') }}"
        pass_l3: "{{ vm_name }}"
        operation: "create"
      tags: [never,create]
```
and
```    - name: "Build inventory"
      include_role:
        name: "passstore/ansible_inventory"
        apply:
          tags:
            - always
      vars:
        pass_l1: "{{ pass_db_name | default('snowdrop') }}"
        pass_l2: "{{ pass_provider | default('hetzner') }}"
        pass_l3: "{{ vm_name }}"
      tags: [always]
```

Questions:
- Is the second one needed ? 
- If yes, can you better document what it does (md file and yml file) ?
- If no, can you fix it please ?
