### ISSUE TITLE
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#211]
## Issue

When we create a new k8s cluster today (= June 29th 2021) using the `kind-reg-ingress.sh` script and deploy an ingress resource as this one

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 0b48b3f6dc69a87d6a84033f28119812b99cd3aa
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: demo
spec:
  rules:
    - host: sb-demo.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: demo
                port:
                  name: http
            path: /
            pathType: Prefix
```

Then, the server returns as response

```
Error from server (InternalError): error when creating "ing-test.yml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
```

Log of the ingress conteoller reports
```
E0629 14:45:32.433880       8 server.go:84] "failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name demo in namespace demo"
```

## Versions used

Ingress yml: `master`
kind : `v0.11.1 go1.16.4 darwin/amd64`
K8s: `1.21.1`
