### ISSUE TITLE
The subnet is not created by ansible...

### ISSUE THREAD

**Issue by jfclere** [snowdrop/k8s-infra#225]
I have used:
ibmcloud is subnet-create jclere-subnet $VPC_ID --zone eu-de-1 --ipv4-address-count 256
to create it.

**Comment by jacobdotcosta** [comment]
Hi @jfclere . I think I need more information on this.

I've just executed the  `vpc-create` playbook and AFAIK it did create the subnet although it doesn't have an associated gateway.

```
$ export IC_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ; export IC_REGION=eu-de
$ ansible-playbook vpc-create.yml
PLAY [Create IBM Cloud VPC VSI] *****************************************************************************************************************...
Thursday 21 October 2021  12:42:20 +0200 (0:00:00.049)       0:00:51.391 ****** 
=============================================================================== 
Configure VPC ------------------------------------------------------ 28.59s
Configure VPC Subnet ----------------------------------------------- 21.73s
Gathering Facts ----------------------------------------------------- 0.95s
Save VPC Subnet as fact --------------------------------------------- 0.05s
Save VPC as fact ---------------------------------------------------- 0.04s
Fetch the variables from var file ----------------------------------- 0.02s
```

Retrieving the subnet information, I used a playbook that I didn't publish yet, I get the following.

```yaml
        "subnets": [
            {
                "available_ipv4_address_count": 251,
                "id": "xxxx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
                "name": "snowdrop-subnet",
                "status": "available",
                "total_ipv4_address_count": 256,
                "zone": "eu-de-1"
            }
        ],
```

Could this be what you mean, that it is missing the Public Gateway?

Thank you.
