### ISSUE TITLE
Some parameters should become optional when we create a new VM on RHOS

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#332]
## Todo

Some parameters should become optional when we create a new VM on RHOS as by example we don't have to use them when we create a new VM where ocp4 will be deployed or used for a different usage

Command executed:
```
ansible-playbook playbook/openstack/openstack_vm_create_passwordstore.yml -e '{"openstack": {"vm": {"network": "provider_net_shared","image": "Fedora-Cloud-Base-35", "flavor": "m1.medium"}}}' -e key_name=test-adm-key -e vm_name=${VM_NAME}
```

Response:
```
TASK [Validate required variables] ********************************************************************************************************************************************************************************************
Thursday 15 June 2023  15:06:15 +0200 (0:00:00.693)       0:00:01.754 ********* 
fatal: [localhost]: FAILED! => {
    "assertion": "k8s_type is defined",
    "changed": false,
    "evaluated_to": false,
    "msg": [
        "Required parameters:",
        "  vm_name: Name of the vm",
        "  pass_provider: provider in the passstore project [hetzner]",
        "  k8s_type: Kubernetes host type [masters,nodes], empty for no k8s installation",
        "  k8s_version: Kubernetes version [115,116], empty for no k8s installation"
    ]
}
```

>**Important**: We cannot make such variables optional without reviewing the code, otherwise will get such an error
```
TASK [Check k8s_type value] ***************************************************************************************************************************************************************************************************
Thursday 15 June 2023  15:13:05 +0200 (0:00:02.828)       0:00:04.647 ********* 
fatal: [localhost]: FAILED! => {
"msg": "The conditional check 'k8s_type != 'masters' and k8s_type != 'nodes' and k8s_type | length > 0' failed. 
The error was: error while evaluating conditional (k8s_type != 'masters' and k8s_type != 'nodes' and k8s_type | length > 0): 'k8s_type' is undefined. 'k8s_type' is undefined

The error appears to be in '/Users/cmoullia/code/snowdrop/k8s-infra/ansible/playbook/passstore/passstore_controller_inventory.yml': line 31, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Check k8s_type value\n      ^ here\n"}
```

**Comment by cmoulliard** [comment]
FYI: Such a change seems to work
```
  pre_tasks:
    - name: "Validate required variables"
      assert:
        that:
          - "vm_name is defined"
          - "pass_provider is defined"
          #- "k8s_type is defined"
          #- "k8s_version is defined"
        fail_msg: 
          - "Required parameters:"
          - "  vm_name: Name of the vm"
          - "  pass_provider: provider in the passstore project [hetzner]"
          #- "  k8s_type: Kubernetes host type [masters,nodes], empty for no k8s installation"
          #- "  k8s_version: Kubernetes version [115,116], empty for no k8s installation"

    - name: "Pull pass git database"
      shell: "git pull"
      args:
        chdir: "{{ lookup('env', 'PASSWORD_STORE_DIR') }}"

    # - name: Check k8s_type value
    #   fail:
    #     msg: "Invalid k8s type {{ k8s_type }}. Should be in [masters,nodes]"
    #   when: "k8s_type != 'masters' and k8s_type != 'nodes' and k8s_type | length > 0"

    # - name: Check k8s_version value
    #   fail:
    #     msg: "Invalid k8s version {{ k8s_version }}. Should be in [119 ... 124]"
    #   when: "k8s_version | length > 0 and not k8s_version in ['119', '121', '123', '124'] "
```
