### ISSUE TITLE
Support to patch/provide another kind config

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#344]
## Request

In some cases, it is needed to patch the kubeadmConfigPatches or let's say to change the default kind config which is used when we install kind using the bash script of this project. That would be create to support such an option 

Example of customized kind config which should be applied to of our own config (if we can)
```
kind create cluster --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-client-id: kube
      oidc-issuer-url: https://keycloak.127.0.0.1.nip.io/realms/master
      oidc-username-claim: email
      oidc-groups-claim: groups
EOF
```
